config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true, length: {minimum: 3, maximum: 15}
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "ログインしてください"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_user.messages.build(message_params)
    if message.save
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]
  
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "ログインできました！"
      redirect_to root_path
    else
      flash.now[:error] = "ログインできません"
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました！"
    redirect_to login_path, status: :see_other
  end


  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "既にログインしています"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui header">
  <i class="smile outline blue icon"></i>
  <div class="content">
    トーク
    <div class="sub header">マイオープンチャット</div>
  </div>
</h2>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid card chatbox">
      <div class="content">
        <div class="ui feed">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted blue edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui card chatbox">
      <div class="content">
        <div class="ui vertical pointing menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="ui <%= type %> message">
    <i class="close icon"></i>
    <div class="header">
      <%= message %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Myチャット", root_path, class: "item" %>
<div class="right menu">
	<div class="ui dropdown item">
		アカウント <i class="dropdown icon"></i>
		<div class="menu">
      <% if logged_in? %>
        <%= link_to 'ログアウト', logout_path, class: "item", data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "ログイン", login_path, class: "item" %>
      <% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mychat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="ui large menu">
      <div class="ui container">
        <%= render "layouts/navigation" %>
      </div>
    </div>
    <div class="ui container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>